const AUDIO_SELECTED = 'AUDIO_SELECTED';
const AUDIO_LOADED = 'AUDIO_LOADED';
const BOOK_SELECTED = 'BOOK_SELECTED';
const PLAY_PAUSE_STATUS = 'PLAY_PAUSE_STATUS';
const UPDATE_PLAY_TIME = 'UPDATE_PLAY_TIME';

export {
  AUDIO_LOADED,
  AUDIO_SELECTED,
  BOOK_SELECTED,
  PLAY_PAUSE_STATUS,
  UPDATE_PLAY_TIME
};
