name: anbabian-app CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.1.0'

    - name: Install yarn
      run: npm install --global yarn

    - uses: actions/checkout@v2
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: Set up cache
      uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn01-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn01-

    - name: Install project dependencies
      #if: steps.yarn-cache.outputs.cache-hit != 'true' # FIXME This is not working on subsequent reruns.
      run: yarn install

    - name: Run unit test
      run: yarn test
